### ISSUE TITLE
PDF template

### ISSUE THREAD

**Issue by Cara-Luca** [jake-mw/CDNTaxReceipts#100]
I'd like to delete the PDF template that I uploaded to the Configure CDN Tax Receipts page. I don't want to replace it with another template, I just want to delete it. Any ideas?

**Comment by KarinG** [comment]
Sorry for the late reply @Cara-Luca - there is no delete button. You'll have to manually remove this setting from the database.

**Comment by KarinG** [comment]
PS -> look for it in the civicrm_setting table -> the variable has the name: receipt_pdftemplate

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
