### ISSUE TITLE
Upgrade Issue: Unknown column 'is_cancelled' in 'field list' 

### ISSUE THREAD

**Issue by bkeevil** [jake-mw/CDNTaxReceipts#104]
I'm upgrading from 1.3.1 to 1.4.0

I ran the upgrade module in CiviCRM and it says the 1.4.0 is installed but the database upgrade failed with `[Error: Upgrade org.civicrm.cdntaxreceipts to revision 1320] Task returned false`.

I found and install.sql file in the sql directory in the source tree. So I dropped both tables and recreated them. 

I backed up the data of the two tables cdntaxreceipts_log and cdntaxreceipts_log_contributions. Disabled foreign key checks.

Then I dropped the two existing tables and recreated the versions for version 1.4.0

The error message I get when I import the data into the new tables is "Unknown column 'is_cancelled' in 'field list' "

But my exported data has the column `is_cancelled` that is not in the version 1.4.0 database.

Edit: The column 'receipt_column' is also in my backed up data but not the database.

What should I do?

Edit: I have a restore point to go back to and start over

**Comment by bkeevil** [comment]
I have manually added those two columns and completed the import, however the CiviCRM extensions module reports that I still have to run the database updates for that module and they still fail with the same error message.

**Comment by KarinG** [comment]
I don't recall '`receipt_column`' or '`is_canceled`' - it's definitively not in the current tables and I can't see these fields referenced in any of the `upgrade_` functions in `Upgrader.php`

Perhaps your instance of 1.3.x was customized by a developer?

**Comment by bkeevil** [comment]
I have no way of knowing. I will delete those columns I guess. The data in them is redundant.
