### ISSUE TITLE
Multilingual : Provide translation mechanism for watermarks

### ISSUE THREAD

**Issue by urlisse** [jake-mw/CDNTaxReceipts#105]
The [_cdntaxreceipts_writeReceipt()](https://github.com/jake-mw/CDNTaxReceipts/blob/master/cdntaxreceipts.functions.inc#L366) function systematically refers to the English images located under the `img` folder. 

In order to support more than one language, the watermarks should either exist in multiple versions and referred to according to the active locale; or, somehow, generated from translated text.

**Comment by urlisse** [comment]
A quick fix/hack might be to copy and translate the content of the `img` folder to a new folder `img/fr` and apply the following change :

```diff
   $pdf_img_files_path = dirname(__FILE__) . '/img/';
+  $lang = substr(CRM_Core_I18n::getLocale(), 0, 2);
+  if (is_dir($pdf_img_files_path . '/' . $lang)) {
+    $pdf_img_files_path = $pdf_img_files_path . '/' . $lang . '/';
+  }
 ```

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
