### ISSUE TITLE
Req: Documentation on generating receipt templates

### ISSUE THREAD

**Issue by bkeevil** [jake-mw/CDNTaxReceipts#106]
I'm having difficulty figuring out how to make a custom receipt template. There is an option at `civicrm/cdntaxreceipts/settings` to upload a custom PDF template but I can't find anything on how to create a template file.

**Comment by KarinG** [comment]
Create a PDF file and upload that. I create our template PDFs with Adobe Photoshop.

**Comment by bkeevil** [comment]
There must be some sort of variable tags that get replaced that I have to add? Otherwise how does the receipt data get into the template?

**Comment by KarinG** [comment]
Look at it like letterhead -> the CiviCRM receipt data gets printed on top of it. Depending on what your template looks like, you may need to make adjustments in the layout - we have a hook for that:

**Example:**

```
function my_receipts_cdntaxreceipts_writeReceipt(&$pdf, $pdf_variables, $receipt) {
  // override some defaults passed in by the cdntaxreceipt extension
  $pdf_variables['mymargin_top'] = 112; 
  ...
}
```

**Comment by bkeevil** [comment]
Understood. The reason I wanted a custom template was to suppress the printing of "Charitable Registration Number". But it doesn't sound like I am going about this the right way. Is there some way to turn that field off?

**Comment by KarinG** [comment]
No you can not switch that off as it’s mandatory under CRA regulations

**Comment by bkeevil** [comment]
Registered political parties, CAs and EDAs can issue tax receipts but are not registered charities and don't have Charitable Registration Numbers.

**Comment by KarinG** [comment]
Exactly so for these you can use a PDF template.

**Comment by bkeevil** [comment]
How can I turn the printing of that field off using a template? You said it was like a letterhead. Do I have to create a custom module?

**Comment by KarinG** [comment]
Yes you need to create a module that calls that hook (see example above) -> in there you decide what gets printed.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
