### ISSUE TITLE
CSS for red background image no longer matches

### ISSUE THREAD

**Issue by martinh-pw** [jake-mw/CDNTaxReceipts#107]
I haven't investigated this very far to see when/if this changed or what else is going on here. But we've been seeing that the background image maple leaf has stopped showing up on the pop-up page for view contribution (on the contact page).

The code in civicrm_cdntaxreceipts.css is using class ui-icon-check, however the site itself appears to have these classes on this span element: ui-button-icon ui-icon fa-check.

So changing the text in that css file from `.ui-icon-check` to `.ui-icon.fa-check` worked for us, lines 14 and 35.

**Comment by KarinG** [comment]
Thanks @martinh-pw - do you want to put that into a PR?

**Comment by martinh-pw** [comment]
Hi @KarinG, I can do that however I'm a bit hesitant because I have really not tested this at all and don't have time today to look at it more closely. I don't know if this would affect other pages or if there's more to look at here. So I wanted to flag it at least, but on my end would rather be a bit more careful with my change before recommending it. :)

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
