### ISSUE TITLE
Wording on CDN TAX RECEIPTS Template

### ISSUE THREAD

**Issue by bullyingcanada** [jake-mw/CDNTaxReceipts#108]
Is there any plan to change the wording on the template that currently says: "Charitable Registration:" to "Charitable Registration Number"?

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
