### ISSUE TITLE
civicrm 5.26.0 and CDNTaxReceipts 1.5.1

### ISSUE THREAD

**Issue by asha15** [jake-mw/CDNTaxReceipts#109]
When i try to install CDNTaxReceipts 1.5.1 into civicrm 5.26.0, i received this error. could i please know any possible fixes ?

![Screenshot from 2020-06-28 01-38-03](https://user-images.githubusercontent.com/28682701/85931268-b52c8400-b8e0-11ea-8e8d-4a940ae20cc2.png)

**Comment by KarinG** [comment]
It sounds like you may have installed this in the past?
