### ISSUE TITLE
Drupal 8 - PHP Fatal error:  require_once(): Failed opening required 'tcpdf/tcpdf.php'

### ISSUE THREAD

**Issue by demeritcowboy** [jake-mw/CDNTaxReceipts#110]
@KarinG  For the issue that came up on the other core PR - if I just make this change in functions.php it seems to get past it:

```patch
-require_once 'tcpdf/tcpdf.php';
+new TCPDF();
```

But then there's a new problem - the settings page gives a 404.

**Comment by KarinG** [comment]
So to confuse things: this is working fine and as is for an older D8 (roundearth method) / 5.24.6 - it has no troubles finding the tcpdf class. I am also looking at their settings page :-)

DrupalCon is about to start but will circle back to this soon. 

This only appeared on a fresh D8 (civicrm asset plugin method):

`Fatal error: require_once(): Failed opening required 'tcpdf/tcpdf.php' (include_path='/var/www/drupal/web/vendor/host/org.civicrm.shoreditch/:/var/www/drupal/web/vendor/host/uk.co.vedaconsulting.mosaico/:/var/www/drupal/web/vendor/host/org.civicrm.flexmailer/:/var/www/drupal/web/vendor/host/ca.civicrm.logviewer/:.:/var/www/drupal/vendor/civicrm/civicrm-core:/var/www/drupal/vendor/civicrm/civicrm-packages:.:/var/www/drupal/vendor/civicrm/civicrm-core/:/var/www/drupal/vendor/civicrm/civicrm-core//packages:/var/www/drupal/vendor/civicrm/civicrm-core/vendor/tecnickcom:/var/www/drupal/vendor/pear/archive_tar:/var/www/drupal/vendor/pear/auth_sasl:/var/www/drupal/vendor/pear/console_getopt:/var/www/drupal/vendor/pear/log:/var/www/drupal/vendor/pear/mail:/var/www/drupal/vendor/pear/net_smtp:/var/www/drupal/vendor/pear/net_socket:/var/www/drupal/vendor/pear/pear-core-minimal/src:/var/www/drupal/vendor/pear/pear_exception:/var/www/drupal/vendor/pear/validate_finance_creditcard:/var/www/drupal/vendor/phpseclib/phpseclib/phpseclib:.: in /var/www/drupal/web/sites/default/files/civicrm/ext/org.civicrm.cdntaxreceipts/cdntaxreceipts.functions.inc on line 3
`

**Comment by demeritcowboy** [comment]
That makes sense though - packages is under civicrm-core in roundearth same as in drupal 7.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
