### ISSUE TITLE
Make contribution source optional

### ISSUE THREAD

**Issue by larssg-wildsight** [jake-mw/CDNTaxReceipts#112]
It would be fantastic if there were a setting to turn off the Source field on the receipt PDF.

It isn't really information we need to provide on a tax receipt and it is potentially weird for donors to see details about their donation method. From the other side, it limits the usefulness of the fairly prominent source field in CiviCRM if one has to be careful to not put anything in that field that shouldn't be shared with the donor.

In particular, we would love to use the new [Referral Source](https://civicrm.org/extensions/referral-source) extension to track donations coming from different emails, website pages, Facebook, Twitter, Insta, etc, but I would be worried about putting this amount of detail on a tax receipt as some donors might feel weird seeing detailed tracking information on their tax receipt.

**Comment by KarinG** [comment]
@larssg-wildsight - there is a hook that allows users to rewrite the tax receipt -> 

`function my_receipts_cdntaxreceipts_writeReceipt(&$pdf, $pdf_variables, $receipt) {
`
and we're using it for your Tax Receipts - so in:
/var/www/html/sites/default/modules/my_receipts/my_receipts.module -> you can alter the lines that write the Source to the 

 ```
 if ($issue_type == 'annual') {
        $pdf->Write(10, ts("Thank you for giving in %1!", array( 1 => $display_year)));
  } 
  else if (strlen($source_funds) < 36 && strlen($source_funds) > 0) {
    $pdf->Write(10, $source_funds);
  }
```

**Comment by larssg-wildsight** [comment]
Thanks @KarinG, done.
