### ISSUE TITLE
Internationalization: Make strings in module translatable

### ISSUE THREAD

**Issue by lolas-freeform** [jake-mw/CDNTaxReceipts#13]
We need the ability to use this module in multiple languages - especially French for Quebec customers.

See https://wiki.civicrm.org/confluence/display/CRMDOC/Extension+translation.

**Comment by LeDucDuBleuet** [comment]
I noticed in current version 1.3.2 that the strings are now enclosed in ts(), how can we provide translations strings in another language?

**Comment by mlutfy** [comment]
From the  [Extension Translation wiki page](https://wiki.civicrm.org/confluence/display/CRMDOC/Extension+translation): « The easiest way to download translations for extensions is to use the "l10nupdate" extension. » This should take care of updating extensions as well.

However, keep in mind that if you use fr_CA, you should store in `/[...]/ext/cdntaxreceipts/l10n/fr_CA/LC_MESSAGES/` (at some point, we should consider auto-sync, as for core).

You can also download the .mo manually from here:
https://download.civicrm.org/civicrm-l10n-extensions/mo/cdntaxreceipts/fr_FR/cdntaxreceipts.mo

To help with the translation:
https://www.transifex.com/civicrm/civicrm_extensions/translate/#fr/cdntaxreceipts/24592320

The .mo file is regenerated every night, or you can compile it yourself using `msgfmt`.

**Comment by LeDucDuBleuet** [comment]
Hello Mathieu, thanks for the quick response!
I tried the l10nupdate extension and it does not work with civicrm 4.6.x, it makes all civicrm pages go in a loop forever. So I copied the cdmtaxreceipts.mo manually in the /ext/cdntaxreceipts/l10n/fr_CA/LC_MESSAGES/ folder and it does translate only the Issue/Re-Issue button. All the rest of the interface and the receipt itself is all in english... :-(

**Comment by mlutfy** [comment]
@LeDucDuBleuet I don't think that's a bug. Those strings may not be translated. Can you double-check in Transifex? You will have to translate them first on Transifex. The ".mo" on download.civicrm.org gets regenated nightly.

**Comment by LeDucDuBleuet** [comment]
@mlutfy Ok thank you for your time, I checked in the .mo and all the strings seem to be translated already. Sorry I don't have time to look further into this and contribute. We needed it only in french so I hardcoded the important strings for now like we were doing for the previous versions. Thanks again and keep up the good work!

**Comment by samuelsov** [comment]
I think this issue is solved and can be closed ?
We have 2 improvements in separate issues though : 
- #69 use the contact preferred language when generating receipts
- #70 have different settings for english / french

**Comment by KarinG** [comment]
Agree @samuelsov - looking forward to working with you on them!
