### ISSUE TITLE
Default Receipt organisation details to the CiviCRM org details

### ISSUE THREAD

**Issue by eileenmcnaughton** [jake-mw/CDNTaxReceipts#16]
I just installed the extension to check it out & the first thing I noticed is that although organisation details are configured on this page civicrm/admin/domain?action=update&reset=1 I still have to enter them on this page civicrm/cdntaxreceipts/settings?reset=1

I think it would be preferable if the tax receipts prefilled from the org details if not configured OR it used them if not configured. The trickiness would be that they would override not update the main details if not altered.

This is definitely in the 'would be more polished with' sort of 'issue' rather than a bug / priority issue - not sure if github allows you to (de) prioritise things once logged?

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
