### ISSUE TITLE
serial vs unique numbering

### ISSUE THREAD

**Issue by ssic** [jake-mw/CDNTaxReceipts#21]
In reference to the bug report/enhancement request at: https://drupal.org/node/2241069
My client says: 
1. Sequential numbering is not required by Revenue Canada (except as outlined in point 3, below), however, when we are audited the auditors will need to see evidence of why numbers are skipped (this info was provided on the phone to me today from the Canada Revenue Agency). Currently, there is no hard evidence to show – there is no report that says “Receipt number XXXX – not issued”.
2. Currently, when a receipt number is skipped, we mark it as “VOID” in our bookkeeping ledger – this results in a lot of VOIDs and will be questioned by our auditors. We have a lot of non-receiptable donations.
3. We use an electronic signature on our receipts, which DOES require serial numbering by the CRA (see excerpt below from http://www.cra-arc.gc.ca/chrts-gvng/chrts/prtng/rcpts/cmptr-eng.html)
Can receipts be issued with facsimile signatures?
A facsimile signature can be used under the following conditions:
a) all copies of receipts are distinctively imprinted (usually by a commercial printer) with the name, address, and registration number of the charity;
b) receipts are serially numbered by a printing press or numbering machine;

**Comment by samuelsov** [comment]
I understand it's not required but some prefer it this way because it facilitate the audit process.
Is there any opposition to add an option so that each installation can choose between the two.
We need to do it for 2 clients so i guess we could propose a patch in that direction.

**Comment by samuelsov** [comment]
There is another issue on this subject : https://github.com/jake-mw/CDNTaxReceipts/issues/71

And even a PR : https://github.com/jake-mw/CDNTaxReceipts/pull/51

So maybe we can close this one ?

**Comment by KarinG** [comment]
Hey @samuelsov - if you can revive that PR - I promise we'll work to get it in - in March;

**Comment by samuelsov** [comment]
ok, i have installed the PR so i will be able to give you more feedback soon, but so far, it seems to work fine.

**Comment by samuelsov** [comment]
We are now using the PR https://github.com/jake-mw/CDNTaxReceipts/pull/51 in 3 production instances with the 2 different use cases : 

- attached with the receipt when the donation happens (live for several month now)
- bulk annual generation of the receipt - we've just did the bulk generation without problem

I think it has been tested enough to merge it in master.

The only thing that we might want to improve is that the numbering is not working in preview mode but I really don't think that it prevent us from merging the PR.

**Comment by KarinG** [comment]
Hi Samuel - there appear to be conflicts (it’s non merge-able); can you have a look at these?

**Comment by samuelsov** [comment]
Sure, i will create a new PR.

**Comment by samuelsov** [comment]
@KarinG the rebase is done -> https://github.com/jake-mw/CDNTaxReceipts/pull/90

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
