### ISSUE TITLE
Wrong amounts when multiple line items of different financial types in a single contribution

### ISSUE THREAD

**Issue by sgladstone** [jake-mw/CDNTaxReceipts#24]
The amount shown on tax receipts (annual and one receipt per contribution) only consider the financial type and amount total for the contribution.    

The numbers are wrong if the contribution has multiple line items, with different financial types on different line items.   

For example:  There is a contribution of $5.00 with financial type "split contribution".  The contribution has 2 line items. First line item: $2. for financial type "Donation"  Second line item: $3. for "School Fees"

In the tax receipt, the amount shows as $5.00 is deductible. (Its looking at the "is deductibe" status from the financial type "split contribution".     This is wrong, only the $2.00 donation is deductible. ( ie the first line item)

**Comment by KarinG** [comment]
I've always discouraged mixing and matching of contribution types for our clients - just weird to have a 'primary' financial type that can be overwritten by a 'sub' financial type - but have a good case on my desk now where a client wants to give people who purchase tickets to an event (not tax deductible) the option to make a donation (tax deductible) on the same registration page. From a fundraising point of view that makes total sense. So I'll be looking into this - this week. Stay tuned.

**Comment by sgladstone** [comment]
IMHO there should NOT be a financial type field on the contribution at all. It should ONLY exist in the line item. ( ie drop the field civicrm_contribution.financial_type_id). 

If the contribution only needs to involves one financial type, then its stored as a contribution with a single line item. ( this is already happening since version 4.2.x)

**Comment by sgladstone** [comment]
FYI: All my clients have a financial type called " -- SPLIT -- " that they use whenever there is a priceset involved.

**Comment by sgladstone** [comment]
Any estimate on when this issue will be fixed?

**Comment by KarinG** [comment]
I spoke with Lola and she has been looking into this. Keep in mind that we're all super busy - helping lots of our clients meet their CRA deadline this month.

**Comment by sgladstone** [comment]
I understand. I am surprised that none of the other organizations ran into this issue.

**Comment by KarinG** [comment]
This is only an issue if the 'primary' contrbution is set to not tax deductible while some of its line items are. One wsy of handling it is to change primary to is tax deductibe and use the eligibleAmount hook to disqualify the portion(s) of the contribution that are not eligible to be receipted.

**Comment by jake-mw** [comment]
This issue has been fixed in the master branch. It will be part of the next release.
