### ISSUE TITLE
Is there a 4.5 version in the works?

### ISSUE THREAD

**Issue by earlallin** [jake-mw/CDNTaxReceipts#25]
We're trying to use this extension in the latest version of civiCRM and we're getting an error:
Fatal error: Cannot pass parameter 7 by reference in C:...civicrm\custom_ext\CDNTaxReceipts\cdntaxreceipts.functions.inc on line 697

Can you let us know if you have a solution for this?

**Comment by KarinG** [comment]
Sorry - all our major CDN TaxReceipt users are on 4.4.x - LTS - so we've not had any drive towards 4.5.x compatibility - I will have a look at what it would take to release a beta for 4.5.x - poke me early next week if I've not gotten back to you by then.

**Comment by earlallin** [comment]
Thanks – will follow up next week.

 

 

Thank you,

 

Earl Allin

REA Inc.

Office: 416-533-3777

Cell: 416-998-8256

**Comment by lolas-freeform** [comment]
I'll take a look at this today. We have some clients on 4.5 now and one tax receipt user that wants to go to 4.5 this week.

**Comment by KarinG** [comment]
Hi! I started at this last night - and solved the issue:

Fatal error: Cannot pass parameter 7 by reference in C:...civicrm\custom_ext\CDNTaxReceipts\cdntaxreceipts.functions.inc on line 697

I've not pushed the code edits up yet - as I've not worked out the (new) buttons styling yet. The code edits are minor and I've added a version check - so should continue to work with < 4.5 - I'll push them into master.

**Comment by lolas-freeform** [comment]
Thanks Karin!  Will you handle the new release as well or do you want some help with that?

**Comment by KarinG** [comment]
I've uploaded the code edits to Master 
I've not edited the info.xml yet - 

It's not ready for release yet - as we can no longer seem to inject CSS into a button - like we used to - on the View Contribution screen -> the white/red maple leafs.

**Comment by earlallin** [comment]
Karin,

 

Thanks so much for doing this!    Is it useable without the CSS change?

 

 

Thank you,

 

Earl Allin

REA Inc.

Office: 416-533-3777

Cell: 416-998-8256

**Comment by KarinG** [comment]
Clone yourself a copy of master and then test things - let me know if you run into any other issues. 

I just spoke to Lola - she is going to look at the CSS for the button today - it's critical as it gives the admin a visual on the View Contribution screen -> which contributions are eligible for receipting but haven't been receipted yet (white maple leaf) - and which contributions are eligible and have been receipted (red maple leaf)

**Comment by earlallin** [comment]
We haven’t seen any other issues so far.  

 

I’ll keep an eye out for the resolution for the CSS issue, and run some additional tests after that.

 

Thanks again for the quick turnaround.

 

 

Thank you,

 

Earl Allin

REA Inc.

Office: 416-533-3777

Cell: 416-998-8256
