### ISSUE TITLE
Error when viewing contributions

### ISSUE THREAD

**Issue by sgladstone** [jake-mw/CDNTaxReceipts#26]
When clicking the "View" link on any contribution, on any contact's contribution tab I get the following error message:

Fatal error: Cannot pass parameter 7 by reference in /home/dev/public_html/pogstone_extensions/CDNTaxReceipts/cdntaxreceipts.functions.inc on line 697

(This is under CiviCRM version 4.5.6 )

**Comment by KarinG** [comment]
Duplicate of #25
