### ISSUE TITLE
Selected contact shows 0 outstanding receipts despite numerous online donations from last year

### ISSUE THREAD

**Issue by jeromydarling** [jake-mw/CDNTaxReceipts#27]
Trying to send a tax receipt to a  donor but I'm seeing this when selecting their record:

https://www.dropbox.com/s/h1qgvwyhvaxevkl/Screenshot%202015-04-13%2009.04.46.png?dl=0

Running there report obviously generates nothing. What's happening here? I think this happened when I issued a bulk receipt to all my donors. Looks like only 4 emails got sent

**Comment by KarinG** [comment]
Have you tried to issue an aggregate receipt -> Preview for that donor? The table in the aggregate screen view provides a breakdown of not-eligible contributions.

**Comment by jeromydarling** [comment]
No. How would I do that? These donations were made via Paypal and are
recurring

**Comment by KarinG** [comment]
Contributions -> Find Contributions -> Contributor Name or Email -> Search
Then select all -> and from Actions: Issue Aggregate Tax Receipts

**Comment by jeromydarling** [comment]
I do not have that option. I only have "Issue Annual Tax Receipts"

**Comment by jeromydarling** [comment]
nevermind, I see it now

**Comment by jeromydarling** [comment]
It's showing all this individuals donations as not eligible? 

https://www.dropbox.com/s/a1ooj5tjqhun5fi/Screenshot%202015-04-13%2015.10.40.png?dl=0

How can I fix that?

**Comment by KarinG** [comment]
There are a number of reasons a contribution can be classified as not eligible in your CiviCRM: the two common ones are: check the financial type (should be set to is_deductible) check the non deductible amount field for these contributions (should be less than the Amount).

**Comment by jeromydarling** [comment]
The type is "Campaign Contribution" - why would that not be deductible?

**Comment by KarinG** [comment]
Whether it is - or not - is defined in your Financial Type settings.

**Comment by jeromydarling** [comment]
got it!
