### ISSUE TITLE
Compatibility with CiviCRM 4.6.x?

### ISSUE THREAD

**Issue by kasiawaka** [jake-mw/CDNTaxReceipts#30]
Hi, I would like to know if anyone is working on bringing this extension to be compatible with 4.6 version? I have an upcoming project and would be happy to contribute time/resources to make it happen soon.

**Comment by jake-mw** [comment]
The development version of the code -- which you can download directly here at github -- works fully with 4.6.x. The current released version at civicrm.org is not yet working with 4.6.

**Comment by kasiawaka** [comment]
Thank you, I confirm that the latest version from GitHub works on CiviCRM 4.6 despite the info.xml indicating it only works for 4.3 and 4.4.
