### ISSUE TITLE
Report templates not showing up

### ISSUE THREAD

**Issue by lkwetter** [jake-mw/CDNTaxReceipts#32]
First, I want to say thank you to everyone that worked on this module. 

The "Tax Receipts - Receipts Issued" and the "Tax Receipts - Receipts Not Issued" reports don't show up. I have the latest release of civiCRM "4.6.10". Everything else is good.

**Comment by KarinG** [comment]
Hi - best to register the templates yourself: to find what you need check the mgd files:

https://github.com/jake-mw/CDNTaxReceipts/blob/master/CRM/Cdntaxreceipts/Form/Report/ReceiptsIssued.mgd.php

https://github.com/jake-mw/CDNTaxReceipts/blob/master/CRM/Cdntaxreceipts/Form/Report/ReceiptsNotIssued.mgd.php
