### ISSUE TITLE
Filter by contact in the reports

### ISSUE THREAD

**Issue by herbdool** [jake-mw/CDNTaxReceipts#33]
I think it would be quite useful to be able to filter by contact in the reports in order to see all the tax receipts issued by an individual. Thanks!

**Comment by KarinG** [comment]
Next time we have a pass at the civicrm/report/cdntaxreceipts/receiptsissued report we can certainly add in a sort (order_bys) for that field - if you get to it before we do - happy to take a PR!

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
