### ISSUE TITLE
Deleting tax receipts when a contact or contrubution is deleted?

### ISSUE THREAD

**Issue by kasiawaka** [jake-mw/CDNTaxReceipts#34]
This is a feature request rather than a bug. When a contact record is deleted in CiviCRM, related contributions etc. are also deleted. Also, when membership record is deleted, contribution is deleted. Should similar functionality work in this extension - when a contribution is deleted, the receipt is deleted? At the moment, the receipts are still in the system and can be reported on, even when the original contribution was removed.

**Comment by jake-mw** [comment]
Hi Kasia,

By maintaining the receipt record when the related contribution/contact is deleted, we maintain an audit trail of issued tax receipts. Once a receipt has been issued, it should theoretically never disappear from the books. This is essentially an anti-fraud feature.

I'm happy to discuss this more if you wish. I think I need help understanding why we want to delete contributions that have been entered and receipted. Should these contributions not stay on the books, too?

- Jake

**Comment by lolas-freeform** [comment]
I tend to agree with you Jake. Except in testing this doesn't seem like it should really happen. In testing the records can be deleted from the DB.

**Comment by KarinG** [comment]
Yes - once a tax receipt has been issued to the donor - it needs stay on record with the organization (I believe the minimum is 7years). Upon CRA request - an organizations needs to be able to explain why a donor got a taxreceipt and how the amount on it was determined - so you will want to keep the contributions too.

**Comment by kasiawaka** [comment]
OK, that make sense. So this is a side note that the tax receipts are not deleted when contributions are deleted and if needed (because those were test tax receipts), they can be removed directly from the database, from both extension tables (cdntaxreceipts_log_contributions and cdntaxreceipts_log)
