### ISSUE TITLE
Make e-mail archive optional.

### ISSUE THREAD

**Issue by johanv** [jake-mw/CDNTaxReceipts#38]
A feature request. I would like to leave the e-mail address for the e-mail archive empty. In which case cdntaxreceipt should not try to send e-mails to the archive.

**Comment by jake-mw** [comment]
Hi Johan,
I agree with Karin's comment that we probably don't want to make this field optional. However the root issue that you raise -- timeouts when running large batches of receipts on certain servers -- is a real one that we need to resolve to ensure we don't "lose" batches of receipts half way through their issuing process. I'm going to move this into a new issue so we don't lose that.
- JMW
