### ISSUE TITLE
Feature request - API to issue tax receipts

### ISSUE THREAD

**Issue by lolaslade** [jake-mw/CDNTaxReceipts#41]
We would like an API to issue tax receipts so that we can easily implement methods of batch issuing tax receipts. We have a need to group contributions in a way that is not supported by single, annual or "aggregate" methods. Rather than implementing a new CRM_Core_Form to support this process we would like the flexibility to use REST API calls, the Drupal batch API or other batch methods to build our process. This requires an API to issue tax receipts (and possibly to log them see #40).

**Comment by lolas-freeform** [comment]
I have started work on this. A couple of questions that come to mind:

1. A standard CiviCRM entity is assumed to support standard action names such as "create", "delete", "get", "getcount", "getfields". What would we do on a "create" API action? Log the receipt or issue it? I assume we would not support delete unless we wanted to make it a synonym for "cancel"?
2. How do we want to record the IP and logged in user id when using the API. This is my initial hack:

```
  $uid = CRM_Utils_System::getLoggedInUfID();
  $uid = empty($uid) ? 1 : $uid;
  $ip = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '';
``

**Comment by jake-mw** [comment]
Re #1 - To date, logging the receipt has been synonymous with issuing it.
With the (pending) addition of a receipt_status field, these two could be
decoupled. I don't have a preference.

But I'm unclear how the API will issue a receipt, since issuing is tied to
a whole lot of mechanisms to generate a PDF and download it. Are we
assuming that 'issuing' through the API is done for email-able receipts
only? How does this work for donors who have no email on file (or who have
otherwise opted out of email receipting)?

**Comment by lolas-freeform** [comment]
My plan for PDF generation is to generate them and leave them in a folder. A future feature could be a page that lists files in that folder and allows bulk download via the web instead of staff having to use FTP.

**Comment by jake-mw** [comment]
I have some thoughts on bulk generation of PDFs, which may help out the API
too. Let's chat during our call next week?

**Comment by lolas-freeform** [comment]
Can you hop on Skype for a quick chat now? I am working on this right now.

**Comment by lolas-freeform** [comment]
I believe this would be easier if we were using the newer rewrite (See #47).  The class has separate methods for sending a PDF to the browser and and for saving a file. There are 2 implementations.

https://github.com/jake-mw/CDNTaxReceipts/blob/print_using_pdf_letter/CRM/Cdntaxreceipts/PDF/GeneratorOriginal.php

https://github.com/jake-mw/CDNTaxReceipts/blob/print_using_pdf_letter/CRM/Cdntaxreceipts/PDF/GeneratorPDFLetter.php

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
