### ISSUE TITLE
Support for CiviCRM 4.7

### ISSUE THREAD

**Issue by johanv** [jake-mw/CDNTaxReceipts#43]
If you use this extension in CiviCRM 4.7, you get error messages like:

> Cannot find unsetter for property CRM_Core_Config::$geocodeMethod

I think I can fix this. I will create a pull request in a minute. :-)

**Comment by redherring05** [comment]
I test CDN in Drupal 7 / civiCRM 4.7.1... and got this message :+1: Sorry but we are not able to provide this at the moment.
Cannot read unrecognized property CRM_Core_Config::$maxImportFileSize.
Return to home page.
