### ISSUE TITLE
Serial Numbering, Revisited

### ISSUE THREAD

**Issue by adixon** [jake-mw/CDNTaxReceipts#45]
The table "cdntaxreceipts_log" has a primary id key that in theory could be used as the official receipt number instead of the contribution id that's in use now.

I can see it's a bit of chicken/egg in that the record would need to be written without the receipt number and then generated from the id to avoid weird race issues (i.e. two receipts being generated simultaneously), although maybe locking is a good idea anyway.

I have a client who really, really wants those numbers to be sequential without so many gaps (most of their contributions are not tax receiptable), so I'm just thinking this through as an option.

Any thoughts?

**Comment by jake-mw** [comment]
I have thought about this also. A number of clients have gotten hung up on
the fact "you don't do serial numbering!" -- whether or not that's a valid
CRA requirement, folks get really worried about it.

If we provided this change, I would like to see this as a configurable
option in the settings (use contribution ID vs. serial numbering for
receipt numbers). I think the primary key in the log table is the way to do
it!

Jake

**Comment by KarinG** [comment]
Yes to that it must be configurable and let's keep default Contribution ID as for auditing it is so transparent and easy if they line up. We've done this since inception - a CRA supervised ok-ed it back then. A BDO accountant/partner was involved. National Charities using these TaxReceipts since inception have passed full external audits (the ones that cost a small fortune). 

Note that CRA used to say serial number on their website - now they say: "unique serial number" - the word unique has been inserted since [and serial certainly would have already implied that]. Yes unique is important. We should not get hung up on words on CRA - however - if an organization wants to go serial vs unique then sure let's give them that option.

**Comment by lolas-freeform** [comment]
I agree that a serial numbering option should be provided for those that want it. However I think that relying on the primary key of the table might not be the best implementation. There are a few ways that can go wrong.

**Comment by adixon** [comment]
Lola - tell me more ... I'm having trouble imagining how it might go wrong, since that field is by definition unique and serially incremented and has a one-to-one relationship with issued receipts, no?

Or, did you have another better idea?

re: configurability - definitely, I'm imaging a checkbox, by default off, that controls the switch.

**Comment by lolas-freeform** [comment]
It is often considered bad practice to expose something to the user that is dependent on the database technology in use. 

It's not a big deal. If the database is properly managed it won't go wrong. I am just adding a vote against.

**Comment by adixon** [comment]
Okay, understood, vote recorded.

**Comment by adixon** [comment]
Okay, I've got a PR for your consideration. Here are two observations:
1. Using the primary key in the log table is not actually going to always generate completely serial numbers because of re-issues which take an id but not a receipt number. But I think it's the right approach anyway.
2. The code sends out receipts before logging them, so we have to generate the number before the record actually gets written, so I used a locking strategy to avoid issues if two people are issuing tax receipts simultaneously (which of course sounds like bad idea anyway, but I suppose that guarantees that someone will try). 

Number 2. makes me wonder if a more robust strategy is to write to the table with a pending flag, then send it, and then mark it as sent. For example, if the server broke between sending out the invoice and before it wrote it, then there would be no record of it having been generated/sent (of course, except for that excellent cc'd email).

**Comment by KarinG** [comment]
re: 2 - we're working on a first pass at tracked openings/ability - that will help with that - and will go one step further than just knowing things got sent. I will check your PR after we've finished taxreceipting all our projects - at the end of the month [along with Johan's 4.7 bits].

**Comment by lolas-freeform** [comment]
I have a customer that wants this right now and was going to apply this pull request as a patch but I do think that some organizations including our current client who want the "serial" number feature are not going to be happy about the duplicates/re-issues creating gaps in the sequence. 

That's another reason I was not so happy about the idea of using the id in the table as is. When we were using the contribution id at least the re-issue had the same "Receipt No.". A really nice way to fix this would be to track receipts and receipt issues in separate tables. A quick fix would be to look up the original number when creating a duplicate.

**Comment by jake-mw** [comment]
I don't believe it serves any purpose to track reissues in the receipt
table. That functionality can likely be removed, in order to track the
original receipt only.

**Comment by lolas-freeform** [comment]
I tested this patch and noticed that it doesn't handle the annual or aggregate receipt generation methods. A bit of refactoring should be done to make getting the receipt number into a function called from the single, annual and aggregate generation functions.

**Comment by adixon** [comment]
Lola: this still keeps the same receipt number for re-issues. Actually, you'll see there was an improvement to the code, which was previously relying on the contribution id = receipt number. Now re-issues use the same receipt number regardless of how it was generated, as you suggest.

re: spaces for re-issues. I believe this shouldn't be an issue. The rules don't preclude gaps, they just need them to be well documented. In this case, it should be a much simpler process to clarify the gaps, which in general are going to be few and far between.

As I recall from the days of paper tax receipts, we actually had to use a new sequence number when re-issuing, because we were using pre-printed invoices.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
