### ISSUE TITLE
Issue Location

### ISSUE THREAD

**Issue by adixon** [jake-mw/CDNTaxReceipts#46]
Apparently, all tax receipts are supposed to include "Issue Location", which is not included in these ones.

http://www.cra-arc.gc.ca/chrts-gvng/chrts/prtng/rcpts/whtnf-eng.html

I checked my old ones and it seems this requirement is not very consistently paid attention to, but it'd be nice to be compliant, and I think not so hard.

Happy to generate a PR unless someone thinks this is a bad idea.

**Comment by jake-mw** [comment]
Hi Alan,

I believe the organization address constitutes the issue location. At
least, that's how we have viewed that requirement.

**Comment by KarinG** [comment]
The address of the Charity [top right] is the Issue Location. So I don't see a compliance issue.

**Comment by adixon** [comment]
Yes, I noted that also, but apparently it's not enough, at least officially, though clearly it's a requirement that is pretty fuzzy. If you read my link, it is clear that the address of the organization and where the receipt is issued are two separate requirements. It kind of makes sense if an organization has multiple locations that are all issuing receipts.

**Comment by KarinG** [comment]
Are we just talking renaming the field printed top right to: Location Issued: (instead of simply printing the City name)?

**Comment by adixon** [comment]
No, it's not the same as the address of the organization.

**Comment by KarinG** [comment]
Ok then how would you go about this? Do some GeoLocate on the IP of the admin hitting the keyboard?

**Comment by adixon** [comment]
No, just an extra static field in the extension configuration page. But a good question - if I'm sitting in Toronto running the receipts and the server is in Timbuktu and I print them via some cloud printing service in Constantinople, what should go in there? Our concepts of location are changing ...

**Comment by KarinG** [comment]
This to me sounds like a dated concept - dating back to paper based offices - not connected through IT. If I were to issue a TaxReceipt for an organization right now I'd have to fill in Denver Airport. As long as this does not confuse organizations who are fine with having their address -only- on the receipt then I'm ok if you add on an optional Location Issued - talk to me about where you think this may fit onto the receipt - it's a little tight as is.

**Comment by jake-mw** [comment]
There's a hook that would allow this to be done on a custom basis also, if
it's a matter of one or two clients insisting on having this field. You
could replace the "source" field with "issue location" in a small custom
module.

**Comment by adixon** [comment]
I do think the extension should support the official documentation on tax receipting out of the box. I agree the concept might be dated, and it's clear that the requirement is not actually needed in the organizations that have been audited so far, but it's an easy enough change and is officially legally required, so might as well, yes?

**Comment by KarinG** [comment]
officially legally required :-) I will check the new layout after we've finished taxreceipting all our projects - at the end of the month [along with Johan's 4.7 bits].

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
