### ISSUE TITLE
Code Review: pdf_letter branch - Contains an object oriented re-write

### ISSUE THREAD

**Issue by lolaslade** [jake-mw/CDNTaxReceipts#47]
As we go forward with some new features it would be nice to use some of the OO code structure in the pdf_letter branch. I believe it will make it easier to move forward with changes.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
