### ISSUE TITLE
CiviCRM 4.7.1 and CDN

### ISSUE THREAD

**Issue by redherring05** [jake-mw/CDNTaxReceipts#54]
I tested CDN last version in Drupal 7 / civiCRM 4.7.1... and got this message : 
"Sorry but we are not able to provide this at the moment.
Cannot read unrecognized property CRM_Core_Config::$maxImportFileSize.
Return to home page."

**Comment by KarinG** [comment]
Yes - not supporting 4.7 yet (see info.xml); will look at this after current TaxReceipting season is over - ie early March

**Comment by redherring05** [comment]
thanks for your fast answer !

**Comment by kasiawaka** [comment]
Any update on this? Is there a more recent version that would be 4.7 compatible?

**Comment by KarinG** [comment]
Sorry - we still have all our projects on 4.6.x LTS and no plans to move any to 4.7.x in the foreseeable future. Happy to look PRs for 4.7.x if compatible with 4.6.x

**Comment by KarinG** [comment]
master branch has been compatible with 4.7 - official release to follow shortly;

**Comment by KarinG** [comment]
Ok time to get this fixed.

**Comment by KarinG** [comment]
Make sure you are running 1.4.0 on 5.3.1
