### ISSUE TITLE
Aggregate Receipts: amount in Preview Table differs from Amount Issued in Preview mode receipt

### ISSUE THREAD

**Issue by KarinG** [jake-mw/CDNTaxReceipts#55]
TaxReceipt Amount: 
in Preview Table: $1838 
on Actual Receipt: $1888 [which is correct]

The Aggregate summary screen counts $50 too much as not eligible. There are dozens of contributions here - of all different types/events/PACs/refunds - so it's not clear which one is not handled properly in determining the not eligible amount in the Aggregate summary screen - but it is done correctly in the Actual Receipt.

**Comment by lolas-freeform** [comment]
More info is needed to determine what the source of the bug may be. 
Can you attach a CSV dump of the contributions table entries for that contact as well as a description of what filters you are using when doing the aggregate search?
If we are lucky that is all we need and we don't need the line items etc.

**Comment by KarinG** [comment]
A CSV dump of the contribution table will not be very helpful - as there are also numerous non-deductible amounts that are determined via hooks. Filters: For a given contact -> Find Contributions -> Previous Year.

**Comment by lolas-freeform** [comment]
Well I think you know better than I do what data is needed to reproduce the issue in this case. Sounds like it might need a copy of the whole site. If you want to contact me offline about how I can get the data then I am definitely willing to look into this one.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
