### ISSUE TITLE
Record address used to issue receipt

### ISSUE THREAD

**Issue by lolaslade** [jake-mw/CDNTaxReceipts#56]
For some organizations it is important to record the address used when issuing the receipt. For example provincial parties that want to make sure all eligible donations are from in-province donors.

This could take the form of copying the entire address somewhere or at least recording the address id that was used at the time. The question of behavior when re-issuing a "duplicate" comes up. Should the old address be used? An option given to "Use updated address"?

**Comment by KarinG** [comment]
You can create a hook to disqualify contributions by a donor with an outside province address. That will also run on the individual contribution screen (it will remove the maple leaf) and it will remove this contribution from the not-issued report - so there is no risk of inadvertently issuing a receipt for it.

**Comment by lolas-freeform** [comment]
Karin,

That is a good custom addition. However, this information is still generally useful in the reports.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
