### ISSUE TITLE
Show address in Receipts Reports

### ISSUE THREAD

**Issue by lolaslade** [jake-mw/CDNTaxReceipts#57]
The receipts reports should show the address that would be used on the receipt. In the case of the "Receipts not Issued" report this is useful preview information for organizations that want to check if addresses are incomplete or outdated. In the case of the "Receipts Issued" report it is useful to show what it would be if it was re-issued. 

A separate issue (#56) has been opened about recording the address that was used. If this was implemented then the "Receipts Issued" report should show this address (probably in addition to the newer one that would be used).

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
