### ISSUE TITLE
Single receipt issued (recorded) twice in 4.6+ with "Enable Popup Forms" turned on

### ISSUE THREAD

**Issue by lolaslade** [jake-mw/CDNTaxReceipts#58]
To replicate:
- Check that the setting "Enable Popup Forms" is turned on at Administer >> Customize Data and Screens >> Display Preferences.
- Find an eligible contribution and issue a single receipt for it in the popup view of the contribution.
- The receipt is recorded in the cdntaxreceipts_log table twice.
- Neither copy is marked as a duplicate

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
