### ISSUE TITLE
Red/White Maple leaf button status indicator

### ISSUE THREAD

**Issue by LeDucDuBleuet** [jake-mw/CDNTaxReceipts#61]
In previous version 1.2.x under CiviCRM 4.4.x, we had a little red/white maple leaf directly on the button indicating the status of the receipt. We seem to have lost this feature in version 1.3.x under CiviCRM 4.6.x. Has it been removed?

Thank you.

**Comment by KarinG** [comment]
It's definitively still there -> did you try clear all caches? Remember that if a contribution is not of a financial type that is eligible to be receipted - then it will not display a maple leaf icon.

**Comment by LeDucDuBleuet** [comment]
Ok thank you for your quick confirmation that the feature is still there. I finally found out that the .css of the extension was simply not loaded due to security restrictions put in place in the Apache configuration for the files/civicrm/extensions folder. I fixed it and the maple leaf indicator is fully working again now. Thank you.

**Comment by KarinG** [comment]
Ah - excellent - glad you solved it.
