### ISSUE TITLE
File to be uploaded lost when there is other error on config page

### ISSUE THREAD

**Issue by JoeMurray** [jake-mw/CDNTaxReceipts#64]
On config page, if you specify a file to upload, eg signature image, and there is an unrelated error on the page, eg no value for 'Attach receipts to automated workflow messages?' then after correcting the error and saving the upload is silently lost.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
