### ISSUE TITLE
WSOD when trying to enable Setup in-kind receipts?

### ISSUE THREAD

**Issue by pradpnayak** [jake-mw/CDNTaxReceipts#66]
CiviCRM version : 4.7.2

Error:

PHP Fatal error:  Call to undefined method CRM_Utils_VersionCheck::singleton() in /var/www/drupal7/sites/all/modules/Extensions/CDNTaxReceipts/cdntaxreceipts.functions.inc on line 1169, referer: http://localhost/drupal7/civicrm/cdntaxreceipts/settings

**Comment by pradpnayak** [comment]
Submitted fix at PR https://github.com/jake-mw/CDNTaxReceipts/pull/67

**Comment by KarinG** [comment]
Thanks @pradpnayak for this - Jake and I decided we're actually going to stop supporting (very) old versions of CiviCRM - so rewriting this little section.
