### ISSUE TITLE
Multilingual : have different settings for English / French

### ISSUE THREAD

**Issue by samuelsov** [jake-mw/CDNTaxReceipts#70]
We should be able to have some bilingual settings to adapt the receipt depending on the language : 
- Organization Name
- address (line 1 / line 2)
- website
- authorized signature text
- organization logo
- pdf template

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
