### ISSUE TITLE
Fiscal vs Calendar Year

### ISSUE THREAD

**Issue by bryancn** [jake-mw/CDNTaxReceipts#71]
When aggregating for combined receipts we should honour the CiviCRM Fiscal Year Start set in Administer CiviCRM>Localization>Date Formats rather than presuming a calendar year.

**Comment by jake-mw** [comment]
Hi Bryan

What's your use case for this? In Canada, tax receipts must be issued respecting the calendar year.

Jake

**Comment by bryancn** [comment]
Hi Jake

Sorry, I know you’re not supporting non-Canadian use. Its a bit cheeky, but I thought if Civi provides the facility, why not use it. 

In NZ tax receipts should be issued using the Tax Year, which for individuals is the same as the Fiscal Year, 1 April - 31 March and is usually the same for corporate entities and charities.

Regards

Bryan

**Comment by jake-mw** [comment]
Got it! We likely won't put our time into this - we're focused on Canada - but if someone submitted a pull request which does not interfere with the Canadian way of doing things (i.e. some kind of configurable option) I'd be happy to consider incorporating it.

We are happy to accommodate uses beyond Canada provided the requirements remain sound for Canadian organizations.

**Comment by lolas-freeform** [comment]
This is a special case of this issue: https://github.com/jake-mw/CDNTaxReceipts/issues/48

**Comment by kenleegit** [comment]
Hand raised. Here in Hong Kong fiscal year starts on 1st of April till end of March next year. So donors require annual receipts of donations made during period.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
