### ISSUE TITLE
Postal Greeting for organization contact type is not respected in tax receipt

### ISSUE THREAD

**Issue by larssg-wildsight** [jake-mw/CDNTaxReceipts#75]
The greeting on tax receipts letter for organization contact type is just Dear [First word of the organization name], instead of the postal greeting, which leads to some strange tax receipt letters starting with "Dear The," or similar.

Version 1.3 on 4.6.33

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
