### ISSUE TITLE
Conflicting Custom field ID

### ISSUE THREAD

**Issue by yosefromano** [jake-mw/CDNTaxReceipts#76]
When installing the extension, I get this error:

Sorry but we are not able to provide this at the moment.
Field: `name` must be unique. An conflicting entity already exists - id: 96

Also, if I try to record a in-kind receipt, the in-kind fields do not show up.

**Comment by pradpnayak** [comment]
@yosefromano I couldn't replicate your issue for unique name field. Please check if the  PR https://github.com/jake-mw/CDNTaxReceipts/pull/78 will resolve your issue.

**Comment by pradpnayak** [comment]
I could replicate this after uninstalling and reinstalling again. The message templates are not deleted from system during uninstall process. I have added a PR that does deletion of message template during uninstall at https://github.com/jake-mw/CDNTaxReceipts/pull/79/files

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
