### ISSUE TITLE
The link to the CRA website is out of date

### ISSUE THREAD

**Issue by freeform-sg** [jake-mw/CDNTaxReceipts#80]
CRA no longer has a dedicated site, it has been incorporated into canada.ca.

The existing link in the PDFs still works and redirects to the new page, though we can't assume that will stay the same.

Current: www.cra-arc.gc.ca/charities
New link (en): www.canada.ca/en/revenue-agency/services/charities-giving/charities.html
New link (fr): www.canada.ca/fr/agence-revenu/services/organismes-bienfaisance-dons/organismes-bienfaisance.html

Unfortunately, it's too long so runs into the thank you text.

![cra_url](https://user-images.githubusercontent.com/2062046/36509018-492209ea-172c-11e8-92a4-94e613991725.png)

**Comment by KarinG** [comment]
Yes noted! We’re working on a different layout option for the receipt that will allow more space not just for this link but also to enable french/translation (that too requires more space)

**Comment by SCMcanada** [comment]
According to the recent Charities and Giving email from CRA you only need to put in: canada.ca/charities-giving

_Official donation receipts must include the name and website address of the Canada Revenue Agency. Following the move to the canada.ca website, official donation receipts will need to be updated with the new address: canada.ca/charities-giving. Charities and qualified donees have until March 31, 2019 to make this change._

**Comment by KarinG** [comment]
Nice - that's easy - can you add a website URL where you found that info - as a reference here? Then I'll make the edit right away.

**Comment by JoeMurray** [comment]
https://github.com/jake-mw/CDNTaxReceipts/pull/81

**Comment by KarinG** [comment]
Nice - Joe - Merci.

**Comment by KarinG** [comment]
Thanks @freeform-sg too!

**Comment by KarinG** [comment]
and @SCMcanada too!

**Comment by freeform-sg** [comment]
Thanks everyone :)

**Comment by SCMcanada** [comment]
Superb! :)
