### ISSUE TITLE
Duplicate tax receipt sent to contributor

### ISSUE THREAD

**Issue by Edzelopez** [jake-mw/CDNTaxReceipts#85]
Hi,

I've enabled CDNTaxReceipts to be emailed to the contributor as part of the workflow, which means the contributor should receive a tax receipt attached to his confirmation receipt. However, the receipt attached to his confirmation receipt is a duplicate one, with the original one (+2 duplicates) being sent to the archive email address. The archive email address also receives a second email with the duplicate receipt attached.

This to me seems like a bug. The original tax receipt (+2 duplicates) should be sent to the original contributor as an attachment to the contribution receipt. The duplicate receipt should be sent to the archive email address.

**Comment by mlutfy** [comment]
Related PR: https://github.com/jake-mw/CDNTaxReceipts/pull/72

**Comment by jake-mw** [comment]
Merged PR #72
