### ISSUE TITLE
Error with bulk actions for issuing tax receipt

### ISSUE THREAD

**Issue by Edzelopez** [jake-mw/CDNTaxReceipts#89]
One of my clients reported this error:

"I think CiviCRM's tax receipt module has a bug. I selected all of the 2018 contributions, and found the Action menu item for Issue Tax Receipt. It said:

You have selected 20 contributions including 7 originals and 13 duplicates to issue. Note that duplicates cannot be issued by this method and will be skipped. The summary below includes the original receipt issue contributions only.  

Seeing that message, I clicked back, to Cancel, and did not issue any receipts. Nonetheless, when I went back in to that module to see if I had missed anything, the numbers had changed to 0 originals and 20 duplicates.

I can persuade it to print ordinary receipts (which are only available one receipt per donation), but not tax receipts. 

However, I did find that if I went into a particular donation and clicked the red maple leaf at the bottom, it took me to a screen where I could reissue the tax receipt, or cancel the tax receipt... and now that I've looked into that a little, the 7 donations where civicrm decided to do its own thing about the tax receipt are all individually receipted."

Please let me know if this is being worked on or if it is a known error. Else, I will be happy to submit a PR for a fix. Thanks!

**Comment by KarinG** [comment]
You’re going to need to be able to reproduce this before reporting it verbatim. I am not convinced it’s possible we’re issuing taxreceipts without someone actually hitting any Issue Tax Receipts buttons.
