### ISSUE TITLE
Checking contribution vs payment date

### ISSUE THREAD

**Issue by martinh-pw** [jake-mw/CDNTaxReceipts#91]
We are having an issue with dates that pertains to the "contributions not receipted" report, but may be a wider issue. In short, the report is using the contribution date as the relevant date for filtering/receipting, rather than the date for the payment item / line item.

We have a contribution with a "date received" in Dec 2018, which has a line item for the full amount in Jan 2019. So it needs to be receipted in 2019 but the report is including it within 2018 when you filter by date.

Yes we could simply change the contribution date, but that's not always possible.

- In this case we are doing accrual accounting so we want to keep the contribution date in Dec to show that promise as being made in Dec.
- The donor could potentially pay a portion in Dec and then another in Jan, which makes the contribution date insufficient.

To clarify a bit more about why it's not a simple workaround on this site, this particular contribution is connected to an event registration, using a price set, so a portion is the event fee and a portion is a donation.

Not sure if anyone else is having this type of issue and/or has recommendations on how to address it? The find contributions page works similarly with the contribution date (not line item date) so that is probably a similar situation, for when we try to issue the receipts?

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
