### ISSUE TITLE
civiCRM 5.14.0 and CdnTaxReceipts 1.4.0

### ISSUE THREAD

**Issue by alexmarketaccess** [jake-mw/CDNTaxReceipts#93]
When a donor makes a contribution, they are emailed a tax receipt -- but it is overlayed with "Duplicate Copy" even though it is the first time they have made a donation.

**Comment by mlutfy** [comment]
You can apply the fix from here: https://github.com/jake-mw/CDNTaxReceipts/pull/72

(It has been fixed in the development version, but there hasn't been an official release recently)

**Comment by alexmarketaccess** [comment]
Thanks for that. I've applied patch, resolves issue. I'll make a separate comment on msg #72

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
