### ISSUE TITLE
civicrm 5.16.2 and CDTaxReceipts 1.5.0

### ISSUE THREAD

**Issue by alexmarketaccess** [jake-mw/CDNTaxReceipts#95]
I'm running under joomla 3.9.11, and when I try to generate a tax receipt, the contribution view page is disabled, and I see the spinning civi icon, and no receipt is generated.

This is what I see: 
https://www.dropbox.com/s/bggtt05wxbuajyl/CDNTaxReceipts.MP4?dl=0

[CiviCRM.fbcf8970092a1d6d64819c89 (1).log](https://github.com/jake-mw/CDNTaxReceipts/files/3516206/CiviCRM.fbcf8970092a1d6d64819c89.1.log)

Hopefully this can be quickly resolved, as I have so many tax receipts to generate!

**Comment by KarinG** [comment]
Hi @alexmarketaccess - sorry to hear that! Paste the relevant lines from your CiviCRM log here in plain text and I'll have a look.

**Comment by alexmarketaccess** [comment]
Thanks for the quick response! I deleted the civiCRM log file and then triggered the error, and attached it above. However, here's the start of it below:

What I notice is the FATAL ERROR line:
SELECT name, title FROM civicrm_option_group**_fr_CA**
Which seems odd, as Joomla and civiCRM are set to use **fr_FR** not fr_CA -- and civicrm_option_group_fr_FR exists (but obviously no fr_CA, ergo the error). Could it be that CDNTaxReceipts is somehow using the wrong language extension?

--------------------------


Aug 19 10:55:39  [info] Deprecated: Group='CDNTaxReceipts'. Name='delivery_method'. Defaults should come from metadata


Aug 19 10:55:41  [info] Deprecated: Group='CDNTaxReceipts'. Name='delivery_method'. Defaults should come from metadata


Aug 19 10:55:41  [info] Deprecated: Group='CDNTaxReceipts'. Name='delivery_method'. Defaults should come from metadata


Aug 19 10:55:41  [info] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => exceptionHandler
        )

    [code] => -18
    [message] => DB Error: no such table
    [mode] => 16
    [debug_info] => SELECT name, title FROM civicrm_option_group_fr_CA [nativecode=1146 ** Table 'fcwm_jom25.civicrm_option_group_fr_CA' doesn't exist]
    [type] => DB_Error
    [user_info] => SELECT name, title FROM civicrm_option_group_fr_CA [nativecode=1146 ** Table 'fcwm_jom25.civicrm_option_group_fr_CA' doesn't exist]
    [to_string] => [db_error: message="DB Error: no such table" code=-18 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="SELECT name, title FROM civicrm_option_group_fr_CA [nativecode=1146 ** Table 'fcwm_jom25.civicrm_option_group_fr_CA' doesn't exist]"]
)

**Comment by KarinG** [comment]
I'm going to ping @samuelsov from Coop Symbiotic (our resident multi-language specialists) - Samuel - do you know what Alex may be running into here? Is that a CiviCRM config?

**Comment by mlutfy** [comment]
Your Preferred Language settings might have "French (Canada)" enabled, instead of "French (France)". I'm not 100% sure, but the code in question is here: https://github.com/jake-mw/CDNTaxReceipts/blob/master/cdntaxreceipts.functions.inc#L1303 (_cdntaxreceipts_setReceiptanguage).

**Comment by KarinG** [comment]
Thanks @mlutfy !

**Comment by alexmarketaccess** [comment]
Did have "French" selected as one of the languages -- this had been this way for years, and CDTaxReceipts worked fine. I changed it to French (France), but they both have the fr value, so I don't think this makes a difference:

![PreferredLang](https://user-images.githubusercontent.com/15691820/63279383-e1b25100-c276-11e9-8ecf-e275d3ab8dcb.png)

This is my Joomla Language Setting:

![JoomlaLang](https://user-images.githubusercontent.com/15691820/63279405-ea0a8c00-c276-11e9-9590-ce4fcb750fc0.png)

And this is the Localization setting:

![LocalizationSetting](https://user-images.githubusercontent.com/15691820/63279479-07d7f100-c277-11e9-92c5-f35682fc71c1.png)

And I still get error:

[debug_info] => SELECT name, title FROM civicrm_option_group_fr_CA [nativecode=1146 ** Table 'fcwm_jom25.civicrm_option_group_fr_CA' doesn't exist]

Any idea how I can write a hack that forces _fr_CA to change be reset to fr_FR (assuming that would resolve issue)?

**Comment by mlutfy** [comment]
@alexmarketaccess Just to confirm: what's the preferred language set on the contact record?

Those option values are a bit annoying. The "fr_CA" / "fr_FR" is set in the "name" property of the option value. You can double-check using the API explorer (Support > Developer > API Explorer)

![Capture d’écran de 2019-08-19 15-51-02](https://user-images.githubusercontent.com/254741/63294792-35ce2d00-c299-11e9-9b9c-ce94e96908cc.png)

**Comment by alexmarketaccess** [comment]
When I set parameters as you show in the screen shot, I get the results:

{

    "is_error": 0,
    "version": 3,
    "count": 1,
    "id": 536,
    "values": [
        {
            "id": "536",
            "option_group_id": "74",
            "label": "French",
            "value": "fr",
            "name": "fr_CA",
            "is_default": "0",
            "weight": "52",
            "is_optgroup": "0",
            "is_reserved": "0",
            "is_active": "0"
        }
    ]
}

**Comment by mlutfy** [comment]
OK - that confirms that the option is indeed not active.

Can you double-check the language preference of the contact?

**Comment by alexmarketaccess** [comment]
I've checked... _Appears_ to be French, but when I click to edit, the field is set to English:

https://www.dropbox.com/s/hjh5wo53gr1h8hx/Language.MP4?dl=0

**Comment by alexmarketaccess** [comment]
Perhaps helpful information -- I tried to generate tax receipt for a contact whose preferred language is English, and that worked fine...

**Comment by mlutfy** [comment]
Can you check the value in the database? It might be that, since fr-CA was disabled, it now defaults to the first option.

You may need to:

- temporarily re-enable fr-CA
- search all fr-CA contacts
- batch update to fr-FR

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
