### ISSUE TITLE
Select contributions by fiscal year

### ISSUE THREAD

**Issue by kenleegit** [jake-mw/CDNTaxReceipts#96]
Pertaining #71 I would like to do quick and dirty by hard-coding the contribution selection criteria to that of fiscal year e.g. from 1st April to 31st Mar instead of calendar year.

Would point me where I could start looking into? Thank you.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
