### ISSUE TITLE
New submitOnce implementation freezes the back button even after batch receipting is finished

### ISSUE THREAD

**Issue by demeritcowboy** [jake-mw/CDNTaxReceipts#98]
I didn't notice this in my original testing of https://github.com/jake-mw/CDNTaxReceipts/pull/94. When you do for example a contribution search, select a couple, and then choose either aggregate or separate receipts from the actions dropdown, you get a batch screen with a Back button and a Download button. Because clicking the download button doesn't navigate away to a new screen like submit buttons on a normal form, the freeziness never goes away, which is good in that you can't re-click Download or mess up the download by clicking Back before it's finished, but bad in that you can't click Back after the download completes.

Personally I rarely use Back or Done buttons on screens and just usually proceed on to whereever else my whims take me, which avoids the problem, but on this screen the Back button does seem useful sometimes.

The original submitOnce function is still available in core and these forms work ok with it, so reverting is temporarily an option.

Some other ideas:
1. I have no unawkward ideas at the moment.

**Comment by KarinG** [comment]
:-) I actually think this was already the case before #94 - a CPA pointed this out to me just before Christmas. I told him (almost) exactly what you you said: it's a feature!

**Comment by KarinG** [comment]
PS and he did not object that his staff had to re-do a search after hitting the checkbox Preview button. It made sense to him.

**Comment by demeritcowboy** [comment]
Odd. I was sure I went back and looked and I just retried just now. Under the old submitOnce the Back button is functional after download, using either the preview checkbox or for real.

Although with the new one I notice the browser back button works just fine to get back to search. What's old is new again.

**Comment by KarinG** [comment]
Ah that must different per browser then. So in a way you’ e made the code more consistent across browsers 👍
