### ISSUE TITLE
No such message template

### ISSUE THREAD

**Issue by Cara-Luca** [jake-mw/CDNTaxReceipts#99]
When I try to distribute a tax receipt, I get this error message.

**No such message template: option group msg_tpl_workflow_cdntaxreceipts, option value cdntaxreceipts_receipt_single.**

or this message

**No such message template: option group msg_tpl_workflow_cdntaxreceipts, option value cdntaxreceipts_receipt_aggregate.**

depending on whether I choose aggregate or single.

**Comment by KarinG** [comment]
If this was an upgrade then you should have been prompted for execute database updates on the Manage Extensions screen.   This was introduced in: public function upgrade_1322() {

**Comment by bkeevil** [comment]
I am having this problem too. How do we run this upgrade?

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
